# Define explícitamente el nombre del Stack para que sea único
name: facturacion-reactiva
version: "3.8"

services:
  app:
    build: .
    # 1. Cambiamos el nombre y añadimos un tag específico para la versión reactiva
    image: facturacion-app:webflux
    ports:
      - "8080:8080"
    environment:
      # 2. Cambiamos el protocolo de conexión de 'jdbc' a 'r2dbc' y usamos postgresql
      DATABASE_URL: r2dbc:postgresql://db:5432/facturacion
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
    depends_on:
      - db

  db:
    # 3. Usamos PostgreSQL en lugar de MySQL
    image: postgres:15-alpine
    container_name: facturacion-db-webflux
    restart: always
    environment:
      POSTGRES_DB: facturacion
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data_webflux:/var/lib/postgresql/data

volumes:
  db_data_webflux: