spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://db:5432/facturacion}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  main:
    web-application-type: reactive

server:
  port: ${PORT:8080}