spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:mysql://db:3306/facturacion
    username: user
    password: password
  main:
    web-application-type: reactive

server:
  port: 8080
